id: netweaver_application_server_java
info:
  name: netweaver_application_server_java
  author: cn-kali-team
  tags: detect,tech,netweaver_application_server_java
  severity: info
  metadata:
    fofa-query:
    - icon_hash=-266008933
    product: netweaver_application_server_java
    shodan-query:
    - http.favicon.hash:-266008933
    vendor: sap
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: favicon
    hash:
    - '-266008933'
