id: sap_web_application_server
info:
  name: sap_web_application_server
  author: cn-kali-team
  tags: detect,tech,sap_web_application_server
  severity: info
  metadata:
    fofa-query:
    - body="sap business server pages team"
    product: sap_web_application_server
    shodan-query:
    - html:"sap business server pages team"
    - http.html:"sap business server pages team"
    vendor: sap
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - sap business server pages team
    case-insensitive: true
