[toolchain]
channel = "stable"
components = ["rustfmt", "clippy"]

#https://rust-lang.github.io/rustup/overrides.html
targets = [
    "x86_64-pc-windows-gnu",
    "i686-pc-windows-gnu",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
]
