id: homebridge-config-ui-x
info:
  name: homebridge-config-ui-x
  author: cn-kali-team
  tags: detect,tech,homebridge-config-ui-x
  severity: info
  metadata:
    fofa-query:
    - title="homebridge"
    product: homebridge-config-ui-x
    shodan-query:
    - http.title:"homebridge"
    vendor: homebridge
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: regex
    regex:
    - (?mi)<title[^>]*>homebridge.*?</title>
