id: netscaler_application_delivery_controller
info:
  name: netscaler_application_delivery_controller
  author: cn-kali-team
  tags: detect,tech,netscaler_application_delivery_controller
  severity: info
  metadata:
    fofa-query:
    - title="citrix gateway" || title:"netscaler gateway"
    google-query:
    - intitle:"citrix gateway" || title:"netscaler gateway"
    product: netscaler_application_delivery_controller
    shodan-query:
    - title:"citrix gateway" || title:"netscaler gateway"
    - http.title:"citrix gateway" || title:"netscaler gateway"
    vendor: citrix
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: regex
    regex:
    - (?mi)<title[^>]*> title:"netscaler gateway.*?</title>
    - (?mi)<title[^>]*>citrix gateway" .*?</title>
