id: docker
info:
  name: Docker remote API
  author: nmap,cn-kali-team
  tags: detect,tech,docker,service
  severity: info
  metadata:
    info: API 1.11 or older
    product: docker
    rarity: 8
    vendor: docker
    verified: true
    version: $1
tcp:
- name: docker
  inputs:
  - data: GET /version HTTP/1.1\r\n\r\n
  host:
  - '{{Hostname}}'
  port: 2375,2379,2380
  extractors:
  - name: docker
    type: regex
    regex:
    - '^HTTP/1\.1 200 OK\r\nContent-Type: application/json\r\nJob-Name: version\r\nDate: .*\r\nContent-Length: \d+\r\n\r\n{.*\"Version\":\"([^"]+)\"'
