name: 添加指纹
description: 添加指纹
title: "添加指纹-[全英文组件名称]"
labels: [ ]
assignees:
  - cn-kali-team
body:
  - type: markdown
    attributes:
      value: |
        请按照提示提交指纹：如果不填写测试目标则无法自动验证指纹，指纹规则按照markdown的Yaml代码格式提交。
  - type: input
    id: target
    attributes:
      label: 测试目标
      description: 填写一个带协议的外网测试目标
      placeholder: "https://www.example.com/"
    validations:
      required: false
  - type: textarea
    id: yaml_data
    attributes:
      label: 指纹的Yaml文件内容
      description: 粘贴你验证过后的Yaml文件内容
      placeholder: "```yaml\n参考0example文件格式\n```"
      value: "
      ```yaml
name: 0example
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: 'base64'
    status_code: 0
    headers: {}
    keyword:
      - <title>Example Domain</title>
    favicon_hash: []
```
"
    validations:
      required: true


