name: 删除指纹
description: 删除指纹
title: "删除指纹-[全英文组件名称]"
labels: [ ]
assignees:
  - cn-kali-team
body:
  - type: markdown
    attributes:
      value: |
        标题填想要删除的指纹就行了。
  - type: input
    id: target
    attributes:
      label: 删除原因
      description: 删除原因
      placeholder: 重复了
    validations:
      required: false


