name: 修改指纹
description: 修改指纹
title: "修改指纹-[全英文组件名称]"
labels: [ ]
assignees:
  - cn-kali-team
body:
  - type: markdown
    attributes:
      value: |
        请按照提示修改指纹：如果不填写测试目标则无法自动验证指纹，指纹规则按照markdown的Yaml代码格式修改。
  - type: markdown
    attributes:
      value: |
        提交前请先在本地验证指纹规则，本地验证示例：
        ```bash
        ➜  ~ ./observer_ward_amd64 --verify 0x727/FingerprintHub/fingerprint/swagger.yaml -t http://httpbin.org
        [ http://httpbin.org |["swagger"] | 9593 | 200 | httpbin.org ]
        Important technology:

        +--------------------+---------+--------+-------------+-------------+----------+
        | url                | name    | length | status_code | title       | priority |
        +====================+=========+========+=============+=============+==========+
        | http://httpbin.org | swagger | 9593   | 200         | httpbin.org | 5        |
        +--------------------+---------+--------+-------------+-------------+----------+
        ```
  - type: input
    id: target
    attributes:
      label: 测试目标
      description: 填写一个带协议的外网测试目标
      placeholder: "https://www.example.com/"
    validations:
      required: false
  - type: textarea
    id: yaml_data
    attributes:
      label: 指纹的Yaml规则
      description: 粘贴你验证过后的Yaml文件内容
      placeholder: "```yaml\n参考0example文件格式\n```"
      value: "
      ```yaml
      
      ```"
    validations:
      required: true


