id: rconfig
info:
  name: rconfig
  author: cn-kali-team
  tags: detect,tech,rconfig
  severity: info
  metadata:
    product: rconfig
    vendor: rconfig
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - rconfiglogo
    case-insensitive: true
