id: ispconfig
info:
  name: ispconfig
  author: cn-kali-team
  tags: detect,tech,ispconfig
  severity: info
  metadata:
    product: ispconfig
    shodan-query:
    - title:"ispconfig" http.favicon.hash:483383992
    - http.title:"ispconfig"
    vendor: ispconfig
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: regex
    regex:
    - (?mi)<title[^>]*>ispconfig" http.favicon.hash:483383992.*?</title>
    - (?mi)<title[^>]*>ispconfig.*?</title>
  - type: word
    words:
    - powered by <a href="http://www.ispconfig.org
    case-insensitive: true
