id: kubernetes
info:
  name: kubernetes
  author: cn-kali-team
  tags: detect,tech,kubernetes
  severity: info
  metadata:
    product: kubernetes
    vendor: kubernetes
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - <article class="post kubernetes
    - <b>kubernetes</b> listening
    - href="assets/images/kubernetes-logo.png
    - value="kubernetes
    case-insensitive: true
  - type: word
    words:
    - 'www-authenticate: realm="kubernetes'
    part: header
    case-insensitive: true
