id: traefik
info:
  name: traefik
  author: cn-kali-team
  tags: detect,tech,traefik
  severity: info
  metadata:
    product: traefik
    vendor: traefik
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: favicon
    hash:
    - 010d94298a0b83cc87846064dc26db44
  - type: word
    words:
    - 'content-security-policy: *.traefik.io;'
    part: header
    case-insensitive: true
