id: prometheus
info:
  name: prometheus
  author: cn-kali-team
  tags: detect,tech,prometheus
  severity: info
  metadata:
    product: prometheus
    vendor: prometheus
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - <title>prometheus
    case-insensitive: true
