id: spring_cloud_config
info:
  name: spring_cloud_config
  author: cn-kali-team
  tags: detect,tech,spring_cloud_config
  severity: info
  metadata:
    fofa-query:
    - body="propertysources" && body="profiles" && body="label"
    product: spring_cloud_config
    shodan-query:
    - http.html:"propertysources"
    vendor: vmware
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - label
    - profiles
    - propertysources
