id: swagger_ui
info:
  name: swagger_ui
  author: cn-kali-team
  tags: detect,tech,swagger_ui
  severity: info
  metadata:
    fofa-query:
    - icon_hash="-1180440057"
    product: swagger_ui
    shodan-query:
    - http.component:"swagger"
    - http.favicon.hash:"-1180440057"
    vendor: smartbear
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: favicon
    hash:
    - '-1180440057'
