id: 360-enterprise-security
info:
  name: 360-enterprise-security
  author: cn-kali-team
  tags: detect,tech,360-enterprise-security
  severity: info
  metadata:
    product: 360-enterprise-security
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - 360entinst
    - 关于全网部署360私有云的通知
    condition: and
    case-insensitive: true
  - type: word
    words:
    - 天擎
    case-insensitive: true
