id: avaya-application-enablement-services
info:
  name: avaya-application-enablement-services
  author: cn-kali-team
  tags: detect,tech,avaya-application-enablement-services
  severity: info
  metadata:
    product: avaya-application-enablement-services
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - <b>application enablement services&nbsp;</b>
    - avaya
    case-insensitive: true
