id: chinatelecomequipmentwebconfigurationsystem
info:
  name: chinatelecomequipmentwebconfigurationsystem
  author: cn-kali-team
  tags: detect,tech,chinatelecomequipmentwebconfigurationsystem
  severity: info
  metadata:
    product: chinatelecomequipmentwebconfigurationsystem
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - 设备web配置</font
    case-insensitive: true
