id: emerson-environmentalenergymonitoringsystem
info:
  name: emerson-environmentalenergymonitoringsystem
  author: cn-kali-team
  tags: detect,tech,emerson-environmentalenergymonitoringsystem
  severity: info
  metadata:
    product: emerson-environmentalenergymonitoringsystem
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - alert("网络断连或者idu-s没有启动.
    case-insensitive: true
