id: gzsa-intranet-security
info:
  name: gzsa-intranet-security
  author: cn-kali-team
  tags: detect,tech,gzsa-intranet-security
  severity: info
  metadata:
    product: gzsa-intranet-security
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - gzsa. all rights reserved</span>
    case-insensitive: true
