id: jurassic-application-management-system
info:
  name: jurassic-application-management-system
  author: cn-kali-team
  tags: detect,tech,jurassic-application-management-system
  severity: info
  metadata:
    product: jurassic-application-management-system
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - jurassic
    - var _usermenusurl = '/appcenter/functions/getusermenu'
    case-insensitive: true
