id: manageengine-applications-manager
info:
  name: manageengine-applications-manager
  author: cn-kali-team
  tags: detect,tech,manageengine-applications-manager
  severity: info
  metadata:
    product: manageengine-applications-manager
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - /appmanager.js
    case-insensitive: true
