id: mission-control-application-shield
info:
  name: mission-control-application-shield
  author: cn-kali-team
  tags: detect,tech,mission-control-application-shield
  severity: info
  metadata:
    product: mission-control-application-shield
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - alt="mission control application shield
    case-insensitive: true
