id: oracle-application-server
info:
  name: oracle-application-server
  author: cn-kali-team
  tags: detect,tech,oracle-application-server
  severity: info
  metadata:
    product: oracle-application-server
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - mod_ose documentation
    - mod_ssl web site
    - oracle http server</font></font></b></h1>
    - oracle jsp documentation
    case-insensitive: true
