id: sap-web-application-server
info:
  name: sap-web-application-server
  author: cn-kali-team
  tags: detect,tech,sap-web-application-server
  severity: info
  metadata:
    product: sap-web-application-server
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - 'server: sap j2ee engine'
    - 'server: sap netweaver application server'
    - 'server: sap web application server'
    part: header
    case-insensitive: true
