id: swagger
info:
  name: swagger
  author: cn-kali-team
  tags: detect,tech,swagger
  severity: info
  metadata:
    product: swagger
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - swagger ui
    - swagger-ui.css
    - swagger-ui.js
    case-insensitive: true
