id: symantec-client-security
info:
  name: symantec-client-security
  author: cn-kali-team
  tags: detect,tech,symantec-client-security
  severity: info
  metadata:
    product: symantec-client-security
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - <!-- symantec client security web based installation -->
    case-insensitive: true
