id: vrv-desktop-application-system
info:
  name: vrv-desktop-application-system
  author: cn-kali-team
  tags: detect,tech,vrv-desktop-application-system
  severity: info
  metadata:
    product: vrv-desktop-application-system
    vendor: 00_unknown
    verified: false
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - <span id="lblvalidcompany" class="validcompany">vrv
    - var vver = $('#hidverify').val();
    case-insensitive: true
