id: next-gen_application_firewall
info:
  name: next-gen_application_firewall
  author: cn-kali-team
  tags: detect,tech,next-gen_application_firewall
  severity: info
  metadata:
    fofa-query:
    - title="sangfor | ngaf"
    product: next-gen_application_firewall
    vendor: sangfor
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: regex
    regex:
    - (?mi)<title[^>]*>sangfor.*?</title>
