id: docker
info:
  name: Docker remote API
  author: nmap,cn-kali-team
  tags: detect,tech,docker,service
  severity: info
  metadata:
    fallback:
    - get-request
    info: API $1
    operating_system: $2
    product: docker
    rarity: 4
    vendor: docker
    verified: true
    version: $3
tcp:
- name: httpoptions
  inputs:
  - data: OPTIONS / HTTP/1.0\r\n\r\n
  host:
  - '{{Hostname}}'
  port: 2301,631,641,3128,5232,6000,8080,8888,9999,10000,10031,37435,49400,80-85
  extractors:
  - name: docker
    type: regex
    regex:
    - '^HTTP/1\.0 200 OK\r\nApi-Version: ([\d.]+)\r\nDocker-Experimental: false\r\nOstype: (.+)\r\nServer: Docker/(\d[\w.-]*) \(.*\)\r\nDate: .*\r\nContent-Length: 0\r\n\r\n'
