id: grafana
info:
  name: grafana
  author: cn-kali-team
  tags: detect,tech,grafana
  severity: info
  metadata:
    product: grafana
    vendor: grafana
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: word
    words:
    - grafana_icon.svg
    - login
    condition: and
    case-insensitive: true
  - type: word
    words:
    - grafana-app
    - 'window.grafanabootdata = '
    case-insensitive: true
