name: emerson-environmentalenergymonitoringsystem
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - alert("网络断连或者idu-s没有启动.
    favicon_hash: []
