name: gzsa-intranet-security
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - gzsa. all rights reserved</span>
    favicon_hash: []
