name: ispconfig
priority: 3
nuclei_tags:
  - []
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - powered by <a href="http://www.ispconfig.org
    favicon_hash: []
