name: rconfig
priority: 1
nuclei_tags:
  - - rconfig
fingerprint:
  - path: /
    request_method: get
    request_headers: {}
    request_data: ''
    status_code: 0
    headers: {}
    keyword:
      - rConfigLogo
    favicon_hash: []
