id: unifi_network_application
info:
  name: unifi_network_application
  author: cn-kali-team
  tags: detect,tech,unifi_network_application
  severity: info
  metadata:
    product: unifi_network_application
    shodan-query:
    - http.title:"unifi network"
    vendor: ui
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: regex
    regex:
    - (?mi)<title[^>]*>unifi network.*?</title>
