id: device-builder
info:
  name: device-builder
  author: cn-kali-team
  tags: detect,tech,device-builder
  severity: info
  metadata:
    product: device-builder
    shodan-query:
    - http.title:"esphome device builder"
    vendor: esphome
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: regex
    regex:
    - (?mi)<title[^>]*>esphome device builder.*?</title>
