id: jboss_enterprise_application_platform
info:
  name: jboss_enterprise_application_platform
  author: cn-kali-team
  tags: detect,tech,jboss_enterprise_application_platform
  severity: info
  metadata:
    fofa-query:
    - title="jboss"
    google-query:
    - intitle:"jboss"
    product: jboss_enterprise_application_platform
    shodan-query:
    - http.title:"jboss"
    - cpe:"cpe:2.3:a:redhat:jboss_enterprise_application_platform"
    - title:"jboss"
    vendor: redhat
    verified: true
http:
- method: GET
  path:
  - '{{BaseURL}}/'
  matchers:
  - type: regex
    regex:
    - (?mi)<title[^>]*>jboss.*?</title>
